# -*- coding: utf-8 -*-
"""onehotencoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13u2qE9oN9CZaBchTm23ClHL36yuxUpXq
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/cars.csv')

df.head()

df['brand'].value_counts()

df['brand'].nunique()

df['fuel'].value_counts()

df['owner'].value_counts()

"""**One hot encoding using pandas**"""

pd.get_dummies(df,columns=['fuel','owner'])

"""**K-1** **OneHotEncoding**"""

pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

"""**OneHotEncoding using Sklearn**"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=42)

X_train.head()

X_test.head()

from sklearn.preprocessing import OneHotEncoder

"""**One Hot Encoding with Top Categories**"""

ohe = OneHotEncoder(drop='first')

ohe.fit_transform(X_train[['fuel','owner']])

X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()

X_test_new=ohe.transform(X_test[['fuel','owner']]).toarray()

X_train[['brand','km_driven']].values

np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

