# -*- coding: utf-8 -*-
"""univariate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOJOSJrKxCoSqCbDNJSVMjS1h2_9tcdG
"""

import pandas as pd
import seaborn as sns

df=pd.read_csv('/train.csv')

df.head()

# sns.countplot(df['Survived'])
df['Survived'].value_counts().plot(kind='bar')

sns.countplot(df['Sex'])
# df['Survived'].value_counts().plot(kind='bar')

# sns.countplot(df['Sex'])
df['Survived'].value_counts().plot(kind='pie', autopct='%.2f')

"""Numerical Data

a. Histogram
"""

import matplotlib.pyplot as plt

plt.hist(df['Age'], bins=50)

"""Distplot"""

sns.distplot(df['Age'])

"""BoxPlot"""

sns.boxplot(df['Age'])

df['Age'].min()

df['Age'].max()

df['Age'].mean()

df['Age'].skew()

